# Generated by Django 3.0.2 on 2020-02-19 13:20

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ParkingSpot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ts_register', models.DateTimeField(default=django.utils.timezone.now)),
                ('ts_update', models.DateTimeField(default=django.utils.timezone.now)),
                ('registrar_uuid', models.CharField(max_length=100)),
                ('longitude', models.CharField(default='0.0', max_length=100)),
                ('latitude', models.CharField(default='0.0', max_length=100)),
                ('voting_available', models.FloatField(default=0)),
                ('voting_unavailable', models.FloatField(default=0)),
                ('confidence_level', models.FloatField(default=0)),
                ('status', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='ParkingZone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100)),
                ('ts_update', models.DateTimeField(default=django.utils.timezone.now)),
                ('description', models.CharField(default='', max_length=1000)),
                ('center_longitude', models.CharField(default='0.0', max_length=100)),
                ('center_latitude', models.CharField(default='0.0', max_length=100)),
                ('credit_charge', models.IntegerField(default=100)),
            ],
        ),
        migrations.CreateModel(
            name='ParticipantMovementLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ts', models.DateTimeField(default=django.utils.timezone.now)),
                ('participant_uuid', models.CharField(db_index=True, max_length=100)),
                ('longitude', models.CharField(default='0.0', max_length=100)),
                ('latitude', models.CharField(default='0.0', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ts', models.DateTimeField(default=django.utils.timezone.now)),
                ('subscriber_uuid', models.CharField(db_index=True, max_length=100)),
                ('credit_charged', models.IntegerField(default=0)),
                ('zone', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.ParkingZone')),
            ],
        ),
        migrations.CreateModel(
            name='Participation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ts_update', models.DateTimeField(default=django.utils.timezone.now)),
                ('participant_uuid', models.CharField(db_index=True, max_length=100)),
                ('longitude', models.CharField(db_index=True, default='0.0', max_length=100)),
                ('latitude', models.CharField(db_index=True, default='0.0', max_length=100)),
                ('availability_value', models.FloatField()),
                ('processed', models.BooleanField(default=False)),
                ('parking_spot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.ParkingSpot')),
            ],
        ),
        migrations.CreateModel(
            name='ParticipantCredit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ts_update', models.DateTimeField(default=django.utils.timezone.now)),
                ('participant_uuid', models.CharField(db_index=True, max_length=100)),
                ('credit_value', models.IntegerField(default=0)),
                ('participation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.Participation')),
            ],
        ),
        migrations.CreateModel(
            name='ParkingZonePolygonGeoPoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('longitude', models.CharField(max_length=100)),
                ('latitude', models.CharField(max_length=100)),
                ('parking_zone', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.ParkingZone')),
            ],
        ),
        migrations.AddField(
            model_name='parkingspot',
            name='zone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.ParkingZone'),
        ),
        migrations.CreateModel(
            name='ParkingAvailabilityLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ts', models.DateTimeField(default=django.utils.timezone.now)),
                ('participant_uuid', models.CharField(db_index=True, max_length=100)),
                ('longitude', models.CharField(default='0.0', max_length=100)),
                ('latitude', models.CharField(default='0.0', max_length=100)),
                ('availability_value', models.FloatField(default=0)),
                ('parking_spot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.ParkingSpot')),
            ],
        ),
        migrations.CreateModel(
            name='ParkingSpotChanges',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ts_change', models.DateTimeField(default=django.utils.timezone.now)),
                ('longitude', models.CharField(db_index=True, default='0.0', max_length=100)),
                ('latitude', models.CharField(db_index=True, default='0.0', max_length=100)),
                ('voting_available', models.FloatField(default=0)),
                ('voting_unavailable', models.FloatField(default=0)),
                ('confidence_level', models.FloatField(default=0)),
                ('status', models.IntegerField(default=0)),
                ('parking_spot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.ParkingSpot')),
            ],
            options={
                'unique_together': {('longitude', 'latitude', 'ts_change')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='parkingspot',
            unique_together={('longitude', 'latitude')},
        ),
    ]
