# Generated by Django 3.0.2 on 2020-02-19 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parkingzone',
            name='credit_charge',
            field=models.IntegerField(default=5),
        ),
    ]
