# Generated by Django 3.0.3 on 2020-02-22 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_parkingspot_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parkingspot',
            name='voting_available',
        ),
        migrations.RemoveField(
            model_name='parkingspot',
            name='voting_unavailable',
        ),
        migrations.RemoveField(
            model_name='parkingspotchanges',
            name='voting_available',
        ),
        migrations.RemoveField(
            model_name='parkingspotchanges',
            name='voting_unavailable',
        ),
        migrations.AddField(
            model_name='parkingspot',
            name='vote_available',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='parkingspot',
            name='vote_unavailable',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='parkingspotchanges',
            name='vote_available',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='parkingspotchanges',
            name='vote_unavailable',
            field=models.IntegerField(default=0),
        ),
    ]
