# Generated by Django 3.0.3 on 2020-02-23 21:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_auto_20200222_0831'),
    ]

    operations = [
        migrations.RenameField(
            model_name='parkingzone',
            old_name='credit_charge',
            new_name='credit_required',
        ),
    ]
