# Generated by Django 3.0.3 on 2020-02-24 00:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_auto_20200223_2326'),
    ]

    operations = [
        migrations.RenameField(
            model_name='parkingavailabilitylog',
            old_name='availability_value',
            new_name='participation_value',
        ),
        migrations.RenameField(
            model_name='participation',
            old_name='availability_value',
            new_name='participation_value',
        ),
        migrations.AddField(
            model_name='participation',
            name='ts_create',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
