# Generated by Django 3.0.3 on 2020-02-24 00:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0008_auto_20200224_0023'),
    ]

    operations = [
        migrations.RenameField(
            model_name='participation',
            old_name='incentive_processed',
            new_name='processed',
        ),
    ]
