# Generated by Django 3.0.3 on 2020-02-24 06:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0009_auto_20200224_0032'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ts', models.DateTimeField(default=django.utils.timezone.now)),
                ('subscriber_uuid', models.CharField(db_index=True, max_length=100)),
                ('email', models.CharField(db_index=True, max_length=100)),
                ('url_validation', models.CharField(db_index=True, max_length=200)),
                ('validated', models.BooleanField(default=False)),
            ],
        ),
    ]
