# Generated by Django 3.0.3 on 2020-02-24 06:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0010_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='url_validation',
            new_name='key_validation',
        ),
    ]
