# Generated by Django 3.0.3 on 2020-02-24 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0011_auto_20200224_0656'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='profile',
            unique_together={('subscriber_uuid', 'email')},
        ),
    ]
