# Generated by Django 3.0.3 on 2020-02-24 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0012_auto_20200224_0657'),
    ]

    operations = [
        migrations.RenameField(
            model_name='parkingspot',
            old_name='status',
            new_name='parking_status',
        ),
        migrations.AlterField(
            model_name='parkingspot',
            name='confidence_level',
            field=models.FloatField(default=1.0),
        ),
    ]
