# Generated by Django 3.0.3 on 2020-02-24 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0014_auto_20200224_1347'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ParkingSpotChanges',
            new_name='ParkingSpotHistory',
        ),
    ]
