# Generated by Django 3.0.3 on 2020-02-24 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0015_auto_20200224_1349'),
    ]

    operations = [
        migrations.RenameField(
            model_name='participation',
            old_name='processed',
            new_name='incentive_processed',
        ),
    ]
