# Generated by Django 3.0.3 on 2020-02-24 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0016_auto_20200224_1358'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='parkingavailabilitylog',
            options={'verbose_name': 'Parking Availability Log', 'verbose_name_plural': 'Parking Availability Logs'},
        ),
        migrations.AlterModelOptions(
            name='parkingspot',
            options={'verbose_name': 'Parking Spot', 'verbose_name_plural': 'Parking Spots'},
        ),
        migrations.AlterModelOptions(
            name='parkingspothistory',
            options={'verbose_name': 'Parking Spot History', 'verbose_name_plural': 'Parking Spot Histories'},
        ),
        migrations.AlterModelOptions(
            name='parkingzone',
            options={'verbose_name': 'Parking Zone', 'verbose_name_plural': 'Parking Zones'},
        ),
        migrations.AlterModelOptions(
            name='parkingzonepolygongeopoint',
            options={'verbose_name': 'Parking Zone Polygon GeoPoint', 'verbose_name_plural': 'Parking Zone Polygon GeoPoints'},
        ),
        migrations.AlterModelOptions(
            name='participantmovementlog',
            options={'verbose_name': 'Participant Movement Log', 'verbose_name_plural': 'Participant Movement Logs'},
        ),
        migrations.AlterModelOptions(
            name='participation',
            options={'verbose_name': 'Participation', 'verbose_name_plural': 'Participations'},
        ),
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': 'Profile', 'verbose_name_plural': 'Profiles'},
        ),
        migrations.AlterModelOptions(
            name='subscription',
            options={'verbose_name': 'Subscription', 'verbose_name_plural': 'Subscriptions'},
        ),
        migrations.AlterUniqueTogether(
            name='parkingzonepolygongeopoint',
            unique_together={('parking_zone', 'longitude', 'latitude')},
        ),
    ]
