# Generated by Django 3.0.3 on 2020-02-24 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0017_auto_20200224_1543'),
    ]

    operations = [
        migrations.RenameField(
            model_name='parkingspothistory',
            old_name='ts_register',
            new_name='ts_latest',
        ),
        migrations.RenameField(
            model_name='parkingspothistory',
            old_name='ts_update',
            new_name='ts_previous',
        ),
        migrations.AlterUniqueTogether(
            name='parkingspothistory',
            unique_together={('longitude', 'latitude', 'ts_latest')},
        ),
    ]
