# Generated by Django 3.0.3 on 2020-02-24 15:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0018_auto_20200224_1556'),
    ]

    operations = [
        migrations.AddField(
            model_name='parkingspothistory',
            name='parking_spot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.ParkingSpot'),
        ),
        migrations.AlterUniqueTogether(
            name='parkingspothistory',
            unique_together={('parking_spot', 'ts_latest')},
        ),
    ]
