# Generated by Django 3.0.3 on 2020-02-24 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0019_auto_20200224_1558'),
    ]

    operations = [
        migrations.AddField(
            model_name='parkingzone',
            name='token',
            field=models.CharField(default='', max_length=100),
        ),
    ]
