# Generated by Django 3.0.3 on 2020-02-26 08:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0020_parkingzone_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='participation',
            name='ts_incentive',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
