# Generated by Django 3.0.3 on 2020-02-26 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0021_participation_ts_incentive'),
    ]

    operations = [
        migrations.AddField(
            model_name='parkingspothistory',
            name='notify_status',
            field=models.BooleanField(default=False),
        ),
    ]
