# Generated by Django 3.0.3 on 2020-03-04 07:04

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0023_participation_previous_value'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscription',
            old_name='ts',
            new_name='ts_subscription',
        ),
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ts_history', models.DateTimeField(default=django.utils.timezone.now)),
                ('participation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.Participation')),
                ('subscription', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.Subscription')),
            ],
        ),
    ]
