# Generated by Django 3.0.3 on 2020-03-04 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0024_auto_20200304_0704'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='subscriber_uuid',
            field=models.CharField(db_index=True, default='', max_length=100),
        ),
    ]
