# Generated by Django 3.0.3 on 2021-05-10 20:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0025_history_subscriber_uuid'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='history',
            options={'verbose_name': 'History', 'verbose_name_plural': 'History'},
        ),
    ]
