# Generated by Django 3.0.2 on 2020-01-30 02:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ts', models.DateTimeField(default=django.utils.timezone.now)),
                ('log_type', models.CharField(max_length=100)),
                ('routing_key_uuid', models.CharField(max_length=100)),
                ('msg', models.CharField(max_length=100)),
                ('longitude', models.FloatField()),
                ('lattitude', models.FloatField()),
                ('value', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='ParkingSlot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ts', models.DateTimeField(default=django.utils.timezone.now)),
                ('log_type', models.CharField(max_length=100)),
                ('routing_key_uuid', models.CharField(max_length=100)),
                ('msg', models.CharField(max_length=100)),
                ('longitude', models.FloatField()),
                ('lattitude', models.FloatField()),
                ('value', models.FloatField()),
                ('status', models.CharField(max_length=100)),
            ],
        ),
    ]
