# Generated by Django 3.0.2 on 2020-01-30 08:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sparkee_common', '0002_auto_20200130_0613'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParkingAvailabilitySubscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ts', models.DateTimeField(default=django.utils.timezone.now)),
                ('participant_uuid', models.CharField(max_length=100)),
                ('longitude', models.FloatField()),
                ('lattitude', models.FloatField()),
                ('radius', models.FloatField()),
            ],
        ),
    ]
