# Generated by Django 3.0.2 on 2020-01-31 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sparkee_common', '0003_parkingavailabilitysubscription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parkingavailabilitylog',
            name='participant_uuid',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='parkingavailabilitysubscription',
            name='participant_uuid',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='parkingslot',
            name='lattitude',
            field=models.FloatField(db_index=True),
        ),
        migrations.AlterField(
            model_name='parkingslot',
            name='longitude',
            field=models.FloatField(db_index=True),
        ),
        migrations.AlterField(
            model_name='participantmovementlog',
            name='participant_uuid',
            field=models.CharField(db_index=True, max_length=100),
        ),
    ]
