# Generated by Django 3.0.2 on 2020-01-31 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sparkee_common', '0004_auto_20200131_1305'),
    ]

    operations = [
        migrations.RenameField(
            model_name='parkingslot',
            old_name='participant_uuid',
            new_name='participant_registrar_uuid',
        ),
    ]
