# Generated by Django 3.0.2 on 2020-01-31 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sparkee_common', '0005_auto_20200131_1306'),
    ]

    operations = [
        migrations.RenameField(
            model_name='parkingavailabilitysubscription',
            old_name='participant_uuid',
            new_name='subscriber_uuid',
        ),
    ]
