# Generated by Django 3.0.2 on 2020-02-03 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sparkee_common', '0006_auto_20200131_1622'),
    ]

    operations = [
        migrations.RenameField(
            model_name='parkingslot',
            old_name='participant_registrar_uuid',
            new_name='registrar_uuid',
        ),
        migrations.AlterField(
            model_name='parkingavailabilitysubscription',
            name='subscriber_uuid',
            field=models.CharField(db_index=True, max_length=100, unique=True),
        ),
    ]
