# Generated by Django 3.0.2 on 2020-02-03 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sparkee_common', '0007_auto_20200203_1205'),
    ]

    operations = [
        migrations.AddField(
            model_name='parkingslot',
            name='status',
            field=models.IntegerField(default=0),
        ),
    ]
