# Generated by Django 3.0.2 on 2020-02-04 01:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sparkee_common', '0009_parkingavailabilitysubscription_subscriber_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataParticipationParkingAvailability',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ts', models.DateTimeField(default=django.utils.timezone.now)),
                ('participant_uuid', models.CharField(db_index=True, max_length=100)),
                ('longitude', models.FloatField()),
                ('lattitude', models.FloatField()),
                ('availability_value', models.FloatField()),
                ('processed', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='InterimParkingAvailability',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ts_from', models.DateTimeField(default=django.utils.timezone.now)),
                ('ts_to', models.DateTimeField(default=django.utils.timezone.now)),
                ('longitude', models.FloatField()),
                ('lattitude', models.FloatField()),
                ('total_available', models.FloatField(default=0)),
                ('total_unavailable', models.FloatField(default=0)),
                ('status', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='ParticipantCredit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ts', models.DateTimeField(default=django.utils.timezone.now)),
                ('participant_uuid', models.CharField(db_index=True, max_length=100)),
                ('credit_value', models.FloatField()),
                ('processed', models.BooleanField(default=False)),
            ],
        ),
        migrations.RenameField(
            model_name='parkingavailabilitylog',
            old_name='value',
            new_name='availability_value',
        ),
        migrations.RenameField(
            model_name='parkingslot',
            old_name='confidence_available',
            new_name='total_available',
        ),
        migrations.RenameField(
            model_name='parkingslot',
            old_name='confidence_unavailable',
            new_name='total_unavailable',
        ),
    ]
