# Generated by Django 3.0.2 on 2020-02-04 08:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sparkee_common', '0012_auto_20200204_0807'),
    ]

    operations = [
        migrations.AddField(
            model_name='parkingslot',
            name='zone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sparkee_common.ParkingZone'),
        ),
    ]
