# Generated by Django 3.0.2 on 2020-02-04 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sparkee_common', '0013_parkingslot_zone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parkingavailabilitysubscription',
            name='radius',
        ),
        migrations.AddField(
            model_name='parkingzone',
            name='description',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
