# Generated by Django 3.0.2 on 2020-02-04 12:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sparkee_common', '0014_auto_20200204_0823'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dataparticipationparkingavailability',
            old_name='ts',
            new_name='ts_update',
        ),
        migrations.RenameField(
            model_name='participantcredit',
            old_name='ts',
            new_name='ts_update',
        ),
        migrations.AddField(
            model_name='participantcredit',
            name='participation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sparkee_common.DataParticipationParkingAvailability'),
        ),
    ]
