# Generated by Django 3.0.2 on 2020-02-04 18:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sparkee_common', '0016_auto_20200204_1342'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataparticipationparkingavailability',
            name='parking_slot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sparkee_common.ParkingSlot'),
        ),
    ]
