# Generated by Django 3.0.2 on 2020-02-04 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sparkee_common', '0017_dataparticipationparkingavailability_parking_slot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parkingslot',
            name='lattitude',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='parkingslot',
            name='longitude',
            field=models.FloatField(),
        ),
    ]
