# Generated by Django 3.0.2 on 2020-02-04 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sparkee_common', '0020_auto_20200204_1918'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dataparticipationparkingavailability',
            old_name='lattitude',
            new_name='latitude',
        ),
        migrations.RenameField(
            model_name='interimparkingavailability',
            old_name='lattitude',
            new_name='latitude',
        ),
        migrations.RenameField(
            model_name='parkingavailabilitylog',
            old_name='lattitude',
            new_name='latitude',
        ),
        migrations.RenameField(
            model_name='parkingavailabilitysubscription',
            old_name='lattitude',
            new_name='latitude',
        ),
        migrations.RenameField(
            model_name='parkingslot',
            old_name='lattitude',
            new_name='latitude',
        ),
        migrations.RenameField(
            model_name='parkingzone',
            old_name='center_lattitude',
            new_name='center_latitude',
        ),
        migrations.RenameField(
            model_name='participantmovementlog',
            old_name='lattitude',
            new_name='latitude',
        ),
    ]
