# Generated by Django 3.0.2 on 2020-02-05 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sparkee_common', '0021_auto_20200204_1929'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parkingslot',
            name='latitude',
            field=models.CharField(db_index=True, default='0.0', max_length=100),
        ),
        migrations.AlterField(
            model_name='parkingslot',
            name='longitude',
            field=models.CharField(db_index=True, default='0.0', max_length=100),
        ),
    ]
