# Generated by Django 3.0.2 on 2020-02-05 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sparkee_common', '0022_auto_20200205_0959'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parkingzone',
            name='description',
            field=models.CharField(db_index=True, default='', max_length=1000),
        ),
    ]
