# Generated by Django 3.0.2 on 2020-02-05 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sparkee_common', '0023_auto_20200205_1307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parkingzone',
            name='description',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
