# Generated by Django 3.0.2 on 2020-02-05 13:20

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sparkee_common', '0024_auto_20200205_1309'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParkingSlotChanges',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ts_change', models.DateTimeField(default=django.utils.timezone.now)),
                ('longitude', models.CharField(db_index=True, default='0.0', max_length=100)),
                ('latitude', models.CharField(db_index=True, default='0.0', max_length=100)),
                ('total_available', models.FloatField(default=0)),
                ('total_unavailable', models.FloatField(default=0)),
                ('status', models.IntegerField(default=0)),
                ('parking_slot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sparkee_common.ParkingSlot')),
            ],
        ),
        migrations.DeleteModel(
            name='InterimParkingAvailability',
        ),
    ]
