# Generated by Django 3.0.2 on 2020-02-05 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sparkee_common', '0025_auto_20200205_1320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parkingslot',
            name='latitude',
            field=models.CharField(default='0.0', max_length=100),
        ),
        migrations.AlterField(
            model_name='parkingslot',
            name='longitude',
            field=models.CharField(default='0.0', max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='parkingslot',
            unique_together={('longitude', 'latitude')},
        ),
        migrations.AlterUniqueTogether(
            name='parkingslotchanges',
            unique_together={('longitude', 'latitude')},
        ),
    ]
