# Generated by Django 3.0.2 on 2020-02-05 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sparkee_common', '0026_auto_20200205_1326'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='parkingslotchanges',
            unique_together={('longitude', 'latitude', 'ts_change')},
        ),
    ]
