# Generated by Django 3.0.2 on 2020-02-05 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sparkee_common', '0028_auto_20200205_1340'),
    ]

    operations = [
        migrations.AddField(
            model_name='parkingslot',
            name='confidence_level',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='parkingslotchanges',
            name='confidence_level',
            field=models.FloatField(default=0),
        ),
    ]
