# Generated by Django 3.0.2 on 2020-02-06 13:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sparkee_common', '0030_auto_20200206_1041'),
    ]

    operations = [
        migrations.AddField(
            model_name='parkingzone',
            name='allowed_minimum_credit',
            field=models.IntegerField(default=100),
        ),
        migrations.CreateModel(
            name='GeoPointsParkingZonePolygon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('longitude', models.CharField(max_length=100)),
                ('latitude', models.CharField(max_length=100)),
                ('parking_zone', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sparkee_common.ParkingZone')),
            ],
        ),
    ]
