# Generated by Django 3.0.2 on 2020-02-06 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sparkee_common', '0031_auto_20200206_1348'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GeoPointsParkingZonePolygon',
            new_name='ParkingZonePolygonGeoPoints',
        ),
    ]
