# Generated by Django 3.0.2 on 2020-02-06 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sparkee_common', '0032_auto_20200206_1349'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ParkingZonePolygonGeoPoints',
            new_name='ParkingZonePolygonGeoPoint',
        ),
    ]
